import numpy as np

# constants
TH_N0 = 1000
TH_MU = 0.02 * np.log(TH_N0)
TH_BETA = 0.02


# constants for validation contour thresholds

TEV_LOW = 0.2
TEV_HIGH = 0.4

REF_XCORR_LOW = 1
REF_XCORR_HIGH = 3

XCORR_LOW = 2
XCORR_HIGH = 3.5

HYPER_LOW = 4
HYPER_HIGH = 40

SPECTRAST_FVAL_LOW = 0.4
SPECTRAST_FVAL_HIGH = 0.7

SPECTRAST_DOT_LOW = 0.4
SPECTRAST_DOT_HIGH = 0.7

PERCOLATOR_LOW = 0
PERCOLATOR_HIGH  = 2

MSGF_RAW_LOW = 50
MSGF_RAW_HIGH = 200
MSGF_DENOVO_LOW = 100
MSGF_DENOVO_HIGH = 200
MSGF_SPEC_EV_LOW = 0.4
MSGF_SPEC_EV_HIGH = 0.6